language: objective-c
xcode_workspace: MBDataEnvironment.xcworkspace
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init

install:
  gem install xcpretty

before_script:
  sudo systemsetup -settimezone America/New_York

script:
- set -o pipefail && xcodebuild -workspace MBDataEnvironment.xcworkspace -scheme 'MBDataEnvironment-iOS' -destination 'platform=iOS Simulator,OS=10.2,name=iPad Pro (9.7 inch)' -destination-timeout 300 clean build | xcpretty
- set -o pipefail && xcodebuild -workspace MBDataEnvironment.xcworkspace -scheme 'MBDataEnvironment-iOS' -destination 'platform=iOS Simulator,OS=10.2,name=iPad Pro (9.7 inch)' -destination-timeout 300 test | xcpretty
- set -o pipefail && xcodebuild -workspace MBDataEnvironment.xcworkspace -scheme 'MBDataEnvironment-macOS' -destination 'platform=macOS' -destination-timeout 300 clean build | xcpretty
- set -o pipefail && xcodebuild -workspace MBDataEnvironment.xcworkspace -scheme 'MBDataEnvironment-macOS' -destination 'platform=macOS' -destination-timeout 300 test | xcpretty
